  # WRITE BANER TO BEGIN
  banner:
   location: classpath:/banner/banner.txt
   
   # WRITE ERROR POR DEFECTO DE APACHE false  Y POR DEFECTO DE SPRING EN true
  server:
    error:
      whitelabel:
        enabled : true
   
  
  
