 # WRITE BANER TO BEGIN
 banner:
  location: classpath:/banner/banner.txt
   
 # WRITE ERROR POR DEFECTO DE APACHE false  Y POR DEFECTO DE SPRING EN true
 server:
   error:
     whitelabel:
       enabled : true
 # JDBC url of the database
 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: lamisma
    
 # Enable logging of SQL statements.   
  jpa:
    show-sql: true
    hibernate:
    #si las enteties corresponde con las tablas, las que mandan son las entidades de java
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      
    
  
    
      
      
   
  
  
